(define (problem shoe_lacing) (:domain shoe) 
(:objects
	eyelet0 eyelet2 eyelet4 eyelet6 eyelet8 knot_l - eyelet_left
	eyelet1 eyelet3 eyelet5 eyelet7 eyelet9 knot_r - eyelet_right
)
(:init
	(aglet_at aglet_a site_left)
	(aglet_at aglet_b site_right)
	(cursor_a eyelet0)
	(cursor_b eyelet1)
	(= (id eyelet0) 0)
	(= (id eyelet1) 1)
	(= (id eyelet2) 2)
	(= (id eyelet3) 3)
	(= (id eyelet4) 4)
	(= (id eyelet5) 5)
	(= (id eyelet6) 6)
	(= (id eyelet7) 7)
	(= (id eyelet8) 8)
	(= (id eyelet9) 9)
	(= (id knot_l) 10)
	(= (id knot_r) 11)
	(next eyelet0 eyelet3)
	(next eyelet1 eyelet2)
	(next eyelet2 eyelet4)
	(next eyelet3 eyelet5)
	(next eyelet4 eyelet7)
	(next eyelet5 eyelet6)
	(next eyelet6 eyelet8)
	(next eyelet7 eyelet9)
	(next eyelet8 knot_l)
	(next eyelet9 knot_r)
)
(:goal (and
	(eyelet_laced eyelet0)
	(eyelet_laced eyelet1)
	(eyelet_laced eyelet2)
	(eyelet_laced eyelet3)
	(eyelet_laced eyelet4)
	(eyelet_laced eyelet5)
	(eyelet_laced eyelet6)
	(eyelet_laced eyelet7)
	(eyelet_laced eyelet8)
	(eyelet_laced eyelet9)
	(aglet_at aglet_a site_left)
	(aglet_at aglet_b site_right)
))
)